#ifndef KNOTTYENTRAILS_GLOBAL_H
#define KNOTTYENTRAILS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(KNOTTYENTRAILS_LIBRARY)
#  define KNOTTYENTRAILS_EXPORT Q_DECL_EXPORT
#else
#  define KNOTTYENTRAILS_EXPORT Q_DECL_IMPORT
#endif

#endif // KNOTTYENTRAILS_GLOBAL_H
